baseURL = 'https://blog.jankerzone.com/'
languageCode = 'en'
title = 'Blog Jankerzone'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableInlineShortcodes = true

[minify]
  disableXML = true
  minifyOutput = true

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 2

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/pages/about/'
  weight = 3

[[menu.main]]
  identifier = 'main-site'
  name = 'Main Site'
  url = 'https://jankerzone.com'
  weight = 4

[params]
  env = 'production'
  title = 'Blog Jankerzone'
  description = 'Almost Curhat Barely Sharing.'
  author = 'Robsan'
  DateFormat = '02 Jan 2006'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    disableHLJS = false
    favicon = '/favicon.ico'

  [params.homeInfoParams]
    Title = 'Happy Reading!'
    Content = """Feel free to explore our blog and discover new insights.

Blog Jankerzone - Almost curhat barely sharing."""

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/jankerzone'

    [[params.socialIcons]]
      name = 'twitter'
      url = 'https://twitter.com/jankerzone'

[markup]
  [markup.highlight]
    noClasses = false
    style = 'monokai'
