baseURL = 'https://example.org/'
languageCode = 'en'
title = 'blog_v2'
theme = 'PaperMod'
paginate = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableInlineShortcodes = true

[minify]
  disableXML = true
  minifyOutput = true

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 2

[params]
  env = 'production'
  title = 'blog_v2'
  description = 'Notes and articles powered by PaperMod.'
  author = 'Author Name'
  DateFormat = '2006-01-02'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    disableHLJS = false
    favicon = '/favicon.ico'

  [params.homeInfoParams]
    Title = 'Welcome to blog_v2'
    Content = """This site uses the PaperMod theme.

Run `hugo new content posts/first-post.md` to add an article, then preview locally with `hugo server`."""

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/username'

[markup]
  [markup.highlight]
    noClasses = false
    style = 'monokai'
